# Generated by Django 4.1.4 on 2022-12-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=None, max_length=50, unique=True, verbose_name='Username'),
            preserve_default=False,
        ),
    ]
